services:
  dev:
    image: vercel-node
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - code:/root/workspaces
      - vs-server:/root/.vscode-server
volumes:
  vs-server: {}
  code: {}